"""add_run_timestamps

Revision ID: 5e138eab5c4c
Revises: abfed2bbe6ff
Create Date: 2026-04-07 18:06:57.113322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e138eab5c4c'
down_revision: Union[str, Sequence[str], None] = 'abfed2bbe6ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('runs', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('runs', sa.Column('response_code', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('_schedule_run_uc'), 'runs', type_='unique')
    op.drop_index(op.f('ix_schedules_next_run_at'), table_name='schedules')
    op.drop_column('schedules', 'cron_expr')
    op.alter_column('targets', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('targets', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('schedules', sa.Column('cron_expr', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_schedules_next_run_at'), 'schedules', ['next_run_at'], unique=False)
    op.create_unique_constraint(op.f('_schedule_run_uc'), 'runs', ['schedule_id', 'scheduled_at'], postgresql_nulls_not_distinct=False)
    op.drop_column('runs', 'response_code')
    op.drop_column('runs', 'completed_at')
    op.drop_column('runs', 'started_at')
    # ### end Alembic commands ###
