"""add_duration_window

Revision ID: abfed2bbe6ff
Revises: 522fb01e15fb
Create Date: 2026-04-07 17:15:42.209721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abfed2bbe6ff'
down_revision: Union[str, Sequence[str], None] = '522fb01e15fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('schedules', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'duration_seconds')
    op.drop_column('schedules', 'created_at')
    # ### end Alembic commands ###
